---
# tasks file for ansible-etcd-cluster
- name: Create systemd drop-in directory
  file: path={{etcd_dropin_dir}} state=directory mode=0755
  sudo: yes

- name: Set peers conf
  sudo: yes
  template: src=10-peers.conf.j2 dest={{etcd_dropin_dir}}/10-peers.conf
  notify: reload systemd

- name: Create env dir
  sudo: yes
  file: path={{env_fragments_dir}} state=directory

- name: Create env fragment
  sudo: yes
  template: src=etcd.env.j2 dest={{env_fragments_dir}}/etcd.env
  notify: refresh environment

- name: Push ca.crt
  sudo: yes
  copy: src={{local_certs}}/{{etcd_ca_host}}/{{etcd_ca_depot}}/ca.crt dest={{etcd_certs_root}}/
  when: etcd_ca_setup

- name: Uncompress certificates
  sudo: yes
  unarchive: src={{local_certs}}/{{etcd_ca_host}}/{{etcd_ca_depot}}/{{inventory_hostname}}.tar dest={{etcd_certs_root}}
  when: etcd_ca_setup

- name: Add etcd-install unit
  sudo: yes
  template: src=etcd-install.service dest=/etc/systemd/system/etcd-install.service
  notify: reload systemd

- name: Set certificate conf
  sudo: yes
  template: src=20-certs.conf.j2 dest={{etcd_dropin_dir}}/20-certs.conf
  when: etcd_ca_setup
  notify: reload systemd
